version: 2
jobs:
  build:

#    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout #

      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: circleci-svenson-maven-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-svenson-maven-{{ checksum "pom.xml" }}

      - run: mvn package -P benchmark # run the actual tests

      - store_test_results:
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/surefire-reports

      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/svenson*.jar
      - store_artifacts:
          path: target/benchmark.md